### PR TITLE
Fix 'react-test-renderer/package' not found

### LINKED ISSUE #2046: Cannot find module 'react-test-renderer/package' from 'ReactSixteenAdapter.js'
### Current behavior
`Cannot find module 'react-test-renderer/package' from 'ReactSixteenAdapter.js'`
Broke in https://github.com/airbnb/enzyme/commit/98154a945390014a9c97e3a4c6d83eac42f3d73f
Changing the import from:
`import { version as testRendererVersion } from 'react-test-renderer/package';`
to
`import { version as testRendererVersion } from 'react-test-renderer';`

Solves the issue for me.

### Expected behavior
No error...

#### API

- [ ] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  3.9.0
| react               |  16.8.4
| react-dom           |  16.8.4
| react-test-renderer | 16.8.4
| adapter (below)     | 

#### Adapter

- [x ] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

### PR DESCRIPTION
**Pull request by zombieJ**
Latest version of 1.11.0 throw error:
```
Cannot find module 'react-test-renderer/package' from 'ReactSixteenAdapter.js'
```

Fixes #2046

### CODE REVIEW

**Comment by zombieJ** [comment]
@ljharb please help to check this.

**Comment by afc163** [comment]
https://www.npmjs.com/package/enzyme-adapter-react-16 `1.11.1` is still not released in npm.

**Comment by ljharb** [comment]
it is now.
