### ISSUE TITLE
Cannot find module 'react-test-renderer/package' from 'ReactSixteenAdapter.js'

### ISSUE THREAD

**Issue by doronpr** [airbnb/enzyme#2046]
### Current behavior
`Cannot find module 'react-test-renderer/package' from 'ReactSixteenAdapter.js'`
Broke in https://github.com/airbnb/enzyme/commit/98154a945390014a9c97e3a4c6d83eac42f3d73f
Changing the import from:
`import { version as testRendererVersion } from 'react-test-renderer/package';`
to
`import { version as testRendererVersion } from 'react-test-renderer';`

Solves the issue for me.

### Expected behavior
No error...

#### API

- [ ] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  3.9.0
| react               |  16.8.4
| react-dom           |  16.8.4
| react-test-renderer | 16.8.4
| adapter (below)     | 

#### Adapter

- [x ] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by youluna** [comment]
We had the same problem: https://travis-ci.com/alibaba-fusion/next/builds/104198552#L667

**Comment by zombieJ** [comment]
Got the same error: https://circleci.com/gh/ant-design/ant-design/63215?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by shpyo** [comment]
Was about to create the same issue xD

**Comment by andreyshuster** [comment]
Same issue here

**Comment by vzhukovsky** [comment]
Same for me. It would be great to get a hotfix asap.

Thanks)

**Comment by ipanasenko** [comment]
Just freeze it to `~1.10.0` for now. No need to write "same here" 100500 times

**Comment by ljharb** [comment]
This shouldn’t break for anyone - node supports importing json files without an extension.

If it’s not working, then your environment is broken.

**Comment by srittau** [comment]
Adding `"json"` to `jest.moduleFileExtensions` in our `package.json` file works around this problem. Still, I consider it a bug in `react-test-renderer` to require this configuration.

**Comment by ljharb** [comment]
Considering that's the default configuration of node itself, it's a bug in your jest configuration.

@srittau if you remove your fix to your jest config, and change the import in the adapter to have an explicit `.json` extension, does that fix the issue for you?

**Comment by srittau** [comment]
@ljharb It does.

I admit that it makes sense for enzyme to expect to be able to include things without extension, according to node's default configuration. I believe the root problem is that jest does not have an option to add to the default list of file extensions in `package.json`, just to replace it. But I think enzyme can help maintainers by changing the import of the json file (a not too common case) to include the suffix.

We now opted to remove `jest.moduleFileExtensions`, since all extensions required by us are now contained in jest's default configuration anyway.

**Comment by ljharb** [comment]
Either way, I'll close this issue by explicitly adding the extension, since that seems to be the best compromise.
