### ISSUE TITLE
react-test-renderer version for react 16.3.2

### ISSUE THREAD

**Issue by xyz92** [airbnb/enzyme#1918]
What version of react-test-renderer is required with react 16.3.2? After updating react from 15.6.2 to 16.3.2 as a part of SPFx version upgrade to 1.7.0, my react tests are failing with error Cannot find module 'react/lib/React' from 'ReactShallowRenderer.js'. Currently I am using "react-test-renderer": "15.5.4". Should I update the packages: 

 "@types/enzyme": "3.1.11",
 "@types/enzyme-adapter-react-15": "1.0.2",
"enzyme": "3.3.0",
 "enzyme-adapter-react-15": "1.7.0"

**Comment by ljharb** [comment]
For react 16.3, try using the 16.3 adapter (and latest enzyme), and don't install your own react-test-renderer (it's pulled in as a dependency).

The react 15 adapter will only work with react 15.

**Comment by xyz92** [comment]
Thank you!
